server:
  port: 7777
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: cloud-gateway-demo
  cloud:
    gateway:
      routes:
      - id: alpha-service
        uri: lb://alpha-service
        predicates:
        - Path=/service1/**, /service2/**, /service3/**, /service4/**
        filters:
          - name: AuthFilter
            args:
              allowedRoles: ROLE_ADMIN
      - id: alpha-service
        uri: lb://alpha-service
        predicates:
          - Path=/service2/**, /service3/**
        filters:
          - name: AuthFilter
            args:
              allowedRoles: ROLE_USER
      - id: authentication-service
        uri: lb://authentication-service
        predicates:
          - Path=/auth/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG